baseURL = 'https://commitconfirm.com'
languageCode = 'en-us'
title = 'Commit Confirm'
theme = [ "hugo-admonitions", "maverick"]

[permalinks]
  pages = "/:slug"

[params]
  logo = '/static/favicon.ico'
  description = "Technical documentation blog by Jimmy Taylor"
  author = 'Jimmy Taylor'
  items = 10

  [params.comments]
    enabled = false
    githubRepo = 'canhtran/maverick'
    theme = 'github-light'


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = -200
  [[menu.main]]
    identifier = "GitHub"
    name = "GitHub"
    url = "https://github.com/consentfactory"
    weight = "-110"
    [menu.main.params]
      newtab = true
  [[menu.main]]
    identifier = "LinkedIn"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/jimmyboise/"
    weight = "-110"
    [menu.main.params]
      newtab = true
  [[menu.main]]
    identifier = "InstantOstrich"
    name = "InstantOstrich"
    url = "https://instantostrich.com/"
    weight = "-100"
    [menu.main.params]
      newtab = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
